function [eta, E_f] = calculate_CE( ...
    u, ...
    E_in, ...
    F_shift, ...
    F_mode, ...
    lens_metric_coords, ...
    wave_metric_coords, ...
    wave_params, ...
    lens_params, ...
    noise_params ...
)
    arguments
        u                   (1,2) double {mustBeNonNan, mustBeFinite}
        E_in                {mustBeMatrix, mustBeNonNan, mustBeNonempty, mustBeFinite}
        F_shift             {mustBeMatrix, mustBeNonNan, mustBeNonempty, mustBeFinite}
        F_mode              {mustBeMatrix, mustBeNonNan, mustBeNonempty, mustBeFinite}
        lens_metric_coords  Mesh_LensMetricCoords
        wave_metric_coords  Mesh_WaveMetricCoords
        wave_params         Parameters_Wave
        lens_params         Parameters_Lens
        noise_params        Parameters_Noise
    end

    E_f = F_shift.*fourier_transform2( ...
        tip_tilt(E_in, wave_metric_coords, wave_params, u/lens_params.f), ...
        wave_metric_coords.dx, ...
        wave_metric_coords.dy ...
    );
    
    num = abs(integrate2( ...
        E_f.*conj(F_mode), ...
        lens_metric_coords.dx, ...
        lens_metric_coords.dy ...
    ))^2;
    norm_E = integrate2( ...
        abs(E_f).^2, ...
        lens_metric_coords.dx, ...
        lens_metric_coords.dy ...
    );
    norm_F = integrate2( ...
        abs(F_mode).^2, ...
        lens_metric_coords.dx, ...
        lens_metric_coords.dy ...
    );

    eta = (num + thermal_noise(noise_params))/(norm_E*norm_F);
end