function result = spgd_algorithm( ...
    E_in, ...
    F_mode, ...
    wave_metric_coords, ...
    lens_metric_coords, ...
    hyper_params, ...
    wave_params, ...
    lens_params, ...
    noise_params ...
)
    arguments
        E_in                {mustBeMatrix, mustBeNonNan, mustBeNonempty, mustBeFinite}
        F_mode              {mustBeMatrix, mustBeNonNan, mustBeNonempty, mustBeFinite}
        wave_metric_coords  Mesh_WaveMetricCoords
        lens_metric_coords  Mesh_LensMetricCoords
        hyper_params        Parameters_Hyper
        wave_params         Parameters_Wave
        lens_params         Parameters_Lens
        noise_params        Parameters_Noise
    end

    result = Result(hyper_params.N_iter);

    % начальный случайный наклон (имитирует случайное положение FSM)
    u = 0.5*lens_params.w_f*(2*rand(1,2) - 1);
    E_in = tip_tilt(E_in, wave_metric_coords, wave_params, u/lens_params.f);
    F_shift = exp(1j*wave_params.k*lens_params.f)/(1j*lens_params.f*wave_params.lambda) ...
                *exp(1j*wave_params.k/(2*lens_params.f)*(lens_metric_coords.X.^2 + lens_metric_coords.Y.^2));

    CE = @(u) calculate_CE( ...
        u, ...
        E_in, ...
        F_shift, ...
        F_mode, ...
        lens_metric_coords, ...
        wave_metric_coords, ...
        wave_params, ...
        lens_params, ...
        noise_params ...
    );
    
    for iter = 1:hyper_params.N_iter
        delta_u = hyper_params.sigma*(2*randi([0,1], 1, 2) - 1);
        [J_plus, ~] = CE(u + delta_u);
        [J_minus, ~] = CE(u - delta_u);
        u = u + hyper_params.gamma/(2*hyper_params.sigma)*(J_plus - J_minus)*delta_u;

        [result.J_hist(iter), E_f] = CE(u);
        result.I_hist{iter} = abs(E_f).^2;
        result.I_cent_hist(iter,:) = centroid( ...
            lens_metric_coords, ...
            result.I_hist{iter} ...
        );
        result.u_hist(iter,:) = u;

        fprintf('iter %d: I_{cent} = [%.3e,%.3e], u=[%.3e,%.3e], J_plus=%.2e, J_minus=%.2e\n', ...
            iter, result.I_cent_hist(1), result.I_cent_hist(2), u(1), u(2), J_plus, J_minus);
    end
end