function cent = centroid(lens_metric_coords, I)
    arguments
        lens_metric_coords  Mesh_LensMetricCoords
        I                   {mustBeMatrix, mustBeNonempty, mustBePositive}
    end

    cent = [ ...
        integrate2( ...
            lens_metric_coords.X.*I, ...
            lens_metric_coords.dx, ...
            lens_metric_coords.dy ...
        ), ... 
        integrate2( ...
            lens_metric_coords.Y.*I, ...
            lens_metric_coords.dx, ...
            lens_metric_coords.dy ...
        ) ...
    ]/integrate2( ...
        I, ...
        lens_metric_coords.dx, ...
        lens_metric_coords.dy ...
    );
end