function phi_phi = phase_spectral_power_density( ...
    wave_number_coords, ...
    wave_params, ...
    turbulence_params, ...
    path_params ...
)
    arguments
        wave_number_coords  Mesh_WaveNumberCoords
        wave_params         Parameters_Wave
        turbulence_params   Parameters_Turbulence
        path_params         Parameters_Path
    end

    coeff = 2*pi*wave_params.k^2*path_params.dz;

    phi_phi = coeff*refractive_spectral_power_density( ...
        wave_number_coords, ...
        turbulence_params ...
    );

    phi_phi(1, 1) = 0;
end