function phase_sub = phase_subharmonics(N_x_sub, N_y_sub, wave_number_coords, wave_params, turbulence_params, path_params)
    arguments
        N_x_sub             (1, 1) double {mustBePositive}
        N_y_sub             (1, 1) double {mustBePositive}
        wave_number_coords  Mesh_WaveNumberCoords
        wave_params         Parameters_Wave
        turbulence_params   Parameters_Turbulence
        path_params         Parameters_Path
    end

    phase_sub = zeros(N_x_sub, N_y_sub);

    for p = 1:path_params.N_subharm
        model_params_sub = Parameters_Model( ...
            "N_x", N_x_sub, ...
            "N_y", N_y_sub, ...
            "L_x", N_x_sub*(2^p)/wave_number_coords.dx, ...
            "L_y", N_y_sub*(2^p)/wave_number_coords.dy ...
        );
        wave_number_coords_sub = Mesh_WaveNumberCoords(model_params_sub);

        phase_sub = phase_sub + random_wave_phase(...
            phase_spectral_power_density( ...
                wave_number_coords_sub, ...
                wave_params, ...
                turbulence_params, ...
                path_params ...
            ),... 
            wave_number_coords_sub...
        );
    end
end