classdef Parameters_All < Parameters
    properties
        wave_params         Parameters_Wave
        turbulence_params   Parameters_Turbulence
        lens_params         Parameters_Lens
        path_params         Parameters_Path
        noise_params        Parameters_Noise
        model_params        Parameters_Model
        hyper_params        Parameters_Hyper
    end

    methods
        function obj = Parameters_All(options)
            arguments
                options.lambda      (1,1) double {mustBePositive}
                options.w_0         (1,1) double {mustBePositive}
                options.L_0         (1,1) double {mustBePositive}
                options.l_0         (1,1) double {mustBePositive}
                options.C_n_2       (1,1) double {mustBePositive}
                options.f           (1,1) double {mustBePositive}
                options.w_f         (1,1) double {mustBePositive}
                options.L           (1,1) double {mustBePositive}
                options.N_screens   (1,1) double {mustBeInteger, mustBePositive}
                options.N_subharm   (1,1) double {mustBeInteger, mustBePositive}
                options.has_noise   (1,1) logical
                options.eta         (1,1) double {mustBePositive}
                options.T           (1,1) double {mustBePositive}
                options.R           (1,1) double {mustBePositive}
                options.delta_f     (1,1) double {mustBePositive} 
                options.N_x         (1,1) double {mustBeInteger, mustBePositive}
                options.N_y         (1,1) double {mustBeInteger, mustBePositive}
                options.L_x         (1,1) double {mustBePositive}
                options.L_y         (1,1) double {mustBePositive}
                options.sigma       (1,1) double {mustBePositive}
                options.gamma       (1,1) double {mustBePositive}
                options.N_iter      (1,1) double {mustBeInteger, mustBePositive}
            end

            obj.wave_params = Parameters_Wave( ...
                "lambda", options.lambda, ...
                "w_0", options.w_0 ...
            );
            obj.turbulence_params = Parameters_Turbulence( ...
                "L_0", options.L_0, ...
                "l_0", options.l_0, ...
                "C_n_2", options.C_n_2 ...
            );
            obj.lens_params = Parameters_Lens( ...
                "f", options.f, ...
                "w_f", options.w_f ...
            );
            obj.path_params = Parameters_Path( ...
                "L", options.L, ...
                "N_screens", options.N_screens, ...
                "N_subharm", options.N_subharm ...
            );
            obj.noise_params = Parameters_Noise( ...
                "has_noise", options.has_noise, ...
                "photodiode_params", Parameters_Photodiode( ...
                    "eta", options.eta, ...
                    "lambda", options.lambda ...
                ), ...
                "T", options.T, ...
                "R", options.R, ...
                "delta_f", options.delta_f ...
            );
            obj.model_params = Parameters_Model( ...
                "N_x", options.N_x, ...
                "N_y", options.N_y, ...
                "L_x", options.L_x, ...
                "L_y", options.L_y ...
            );
            obj.hyper_params = Parameters_Hyper( ...
                "sigma", options.sigma, ...
                "gamma", options.gamma, ...
                "N_iter", options.N_iter ...
            );
        end
    end

    methods (Access = private)
        function obj = validateScales(obj)
            d_x = obj.model_params.L_x/obj.model_params.N_x;
            d_y = obj.model_params.L_y/obj.model_params.N_y;
            r_0 = fried_parameter( ...
                obj.wave_params.lambda, ...
                obj.path_params.L, ...
                obj.turbulence_params.C_n_2 ...
            );
            z_R = rayleigh_radius( ...
                obj.wave_params.lambda, ...
                obj.wave_params.w_0 ...
            );
            w_dif = obj.wave_params.w_0*(obj.path_params.L/z_R);
            w_turb = 4*obj.path_params.L/(obj.wave_params.k*r_0);
            w_L = sqrt(w_0^2 + w_dif^2 + 2*w_turb^2);
            N_min_1 = 16*obj.path_params.L/(obj.wave_params.k*r_0^2);
            N_min_2 = 12*w_L/obj.turbulence_params.l_0;

            assert(min(obj.model_params.L_x, obj.model_params.L_y) >= 3*obj.wave_params.w_0, ...
                'Расчётная область слишком мала: должна быть не менее 3*w_{0} (текущая L_{x} = %g, L_{y} = %g, w_{0} = %g)', ...
                obj.model_params.L_x, ...
                obj.model_params.L_y, ...
                obj.wave_params.w_0 ...
            );
            assert( ...
                max(d_x, d_y) <= r_0/2, ...
                'Шаг дискретизации dx = %g и dy = %g должен быть не более r_{0}/2 = %g', ...
                d_x, ...
                d_y, ...
                r_0/2 ...
            );
            assert( ...
                min(obj.model_params.N_x, obj.model_params.N_y) >= 128, ...
                'Сетка слишком грубая: используйте хотя бы 128x128' ...
            );
            assert( ...
                obj.lens_params.w_f <= min(obj.model_params.L_x, obj.model_params.L_y)/2, ...
                'Пятно на линзе (w_f = %g) шире половины апертуры (%g)', ...
                obj.lens_params.w_f, ...
                min(obj.model_params.L_x, obj.model_params.L_y)/2 ...
            );
            assert( ...
                obj.model_params.N_x >= N_min_1 && obj.model_params.N_y >= N_min_1, ...
                'Сетка нарушает условие конерентности поля: r_{0} = %g, N_{x} = %g, N_{y} = %g, N_{min} = %g', ...
                r_0, ...
                obj.model_params.N_x, ...
                obj.model_params.N_y, ...
                N_min_1 ...
            );
            assert( ...
                obj.model_params.N_x >= N_min_2 && obj.model_params.N_y >= N_min_2, ...
                'Сетка не разрешает внутренний масштаб турбулентности: l_{0} = %g, N_{x} = %g, N_{y} = %g, N_{min} = %g', ...
                obj.turbulence_params.l_0, ...
                obj.model_params.N_x, ...
                obj.model_params.N_y, ...
                N_min_2 ...
            );
            assert( ...
                obj.noise_params.photodiode_params.eta >= 0 && obj.noise_params.photodiode_params.eta <= 1, ...
                'Квантовая эффективность должна быть в диапазоне от 0 до 1, \eta = %g', ...
                obj.noise_params.photodiode_params.eta ...
            );
        end
    end
end