clear; clc; close all;

all_params = Parameters_All( ...
    "lambda", 1550e-9, ...
    "w_0", 25e-3, ...
    "L_0", 1e0, ...
    "l_0", 1e-3, ...
    "C_n_2", 1e-14, ...
    "f", 3e-1, ...
    "w_f", 4.75e-6, ...
    "L", 1e3, ...
    "N_screens", 50, ...
    "N_subharm", 5, ...
    "has_noise", true, ...
    "eta", 8e-1, ...
    "T", 300, ...
    "R", 100e6, ...
    "delta_f", 10e3, ...
    "N_x", 1024, ...
    "N_y", 1024, ...
    "L_x", 8e0, ...
    "L_y", 8e0, ...
    "sigma", 5e-6, ...
    "gamma", 1e-5, ...
    "N_iter", 100 ...
);

all_meshs = Mesh_All(all_params);

fftw('planner','measure');

[E_in, F_mode] = original_fields( ...
    all_params, ...
    all_meshs ...
);

E_out = propogate( ...
    E_in, ...
    all_meshs.wave_number_coords, ...
    all_meshs.wave_inv_metric_coords, ...
    all_params.wave_params, ...
    all_params.turbulence_params, ...
    all_params.path_params ...
);

spgd_result = spgd_algorithm( ...
    E_out, ...
    F_mode, ...
    all_meshs.wave_metric_coords, ...
    all_meshs.lens_metric_coords, ...
    all_params.hyper_params, ...
    all_params.wave_params, ...
    all_params.lens_params, ...
    all_params.noise_params ...
);

uifig = uifigure();
uifig.Name = ': Интерактивная визуализация';
uifig.NumberTitle = 'on';
uifig.Position = [100 100 1400 600];

gl = uigridlayout(uifig, [2, 2]);
gl.ColumnWidth = {'1x', '1x'};
gl.RowHeight = {'1x', 'fit'};

I_axes = uiaxes(gl); 
I_axes.Layout.Row = 1;
I_axes.Layout.Column = 1;

J_axes = uiaxes(gl);
J_axes.Layout.Row = 1:2;
J_axes.Layout.Column = 2;

sld = uislider(gl);
sld.Layout.Row = 2;
sld.Layout.Column = 1;

[I_img, I_mu, I_mc, J_mi] = make_plots( ...
    all_params, ...
    all_meshs, ...
    spgd_result, ...
    I_axes, ...
    J_axes ...
);

make_interaction( ...
    all_params, ...
    spgd_result, ...
    I_img, ...
    I_mu, ...
    I_mc, ...
    J_mi, ...
    I_axes, ...
    sld ...
);