clear; clc; close all;

fftw('planner','measure');

all_params = Parameters_All( ...
    "lambda", 1550e-9, ...
    "w_0", 5e-3, ...
    "L_0", 1e0, ...
    "l_0", 1e-3, ...
    "C_n_2", 1e-13, ...
    "f", 3e-1, ...
    "w_f", 4.75e-6, ...
    "L", 1e3, ...
    "N_screens", 50, ...
    "N_subharm", 5, ...
    "has_noise", true, ...
    "eta", 8e-1, ...
    "T", 300, ...
    "R", 100e6, ...
    "delta_f", 10e3, ...
    "N_x", 4096, ...
    "N_y", 4096, ...
    "L_x", 1e0, ...
    "L_y", 1e0, ...
    "sigma", 5e-6, ...
    "gamma", 1e-5, ...
    "N_iter", 100 ...
);

all_meshs = Mesh_All(all_params);

[E_in, ~] = original_fields( ...
    all_params, ...
    all_meshs ...
);

I = abs(E_in).^2;

gif_filename = sprintf( ...
    'examples/beam_propagate/beam_propagate_%.3e_%.3e_%.3e_%.3e_%.3e.gif', ...
    all_params.turbulence_params.C_n_2,...
    all_params.turbulence_params.L_0,...
    all_params.turbulence_params.l_0,...
    all_params.path_params.N_screens,...
    all_params.path_params.N_subharm...
);
delay = 10/all_params.path_params.N_screens;
step = 1;

x = all_meshs.wave_metric_coords().X(1,:);
y = all_meshs.wave_metric_coords().Y(:,1);

fig = figure();
fig.Visible = 'off';
fig.ThemeMode = 'manual';
fig.Theme = 'light';
fig.Color = [1 1 1];
fig.Position = groot().ScreenSize;

ax1 = subplot(1,1,1);
ax1.XLim = [x(1) x(end)];
ax1.YLim = [y(1) y(end)];
ax1.DataAspectRatio = [1 1 1];
ax1.DataAspectRatioMode = 'manual';
ax1.PlotBoxAspectRatioMode = 'auto';
ax1.Colormap = colormap(ax1, 'hot');
ax1.Title.String = sprintf('Интенсивность (z = 0 м)');
ax1.XLabel.String = 'x (м)';
ax1.YLabel.String = 'y (м)';
ax1.FontSize = 16;

hold(ax1, 'on');

img1 = imagesc(ax1, x, y, I);
img1.Interpolation = 'bilinear';

drawnow;

for iter = 1:all_params.path_params.N_screens
    fprintf("iter = %d\n", iter);

    phase = phase_screen(all_meshs.wave_number_coords, all_params.wave_params, all_params.turbulence_params, all_params.path_params);
    E_in = phase_shift(E_in, phase);
    E_in = fresnel_propagate(E_in, all_meshs.wave_inv_metric_coords, all_params.wave_params, all_params.path_params);

    I = abs(E_in).^2;

    ax1.Title.String = sprintf( ...
        'Интенсивность (z = %.2f м)', ...
        iter*all_params.path_params.dz ...
    );
    img1.CData = I;
    
    drawnow;
    
    [A, map] = rgb2ind(frame2im(getframe(fig)), 256);
    
    if iter == 1
        imwrite( ...
            A, map, gif_filename, 'gif', ...
            'LoopCount', Inf, ...
            'DelayTime', delay ...
        );
    else
        imwrite( ...
            A, map, gif_filename, 'gif', ...
            'WriteMode', 'append', ...
            'DelayTime', delay ...
        );
    end
end

close(fig);
fprintf('GIF сохранён: %s\n', gif_filename);