clear; clc; close all;

all_params = Parameters_All( ...
    "lambda", 1550e-9, ...
    "w_0", 25e-3, ...
    "L_0", 1e0, ...
    "l_0", 1e-3, ...
    "C_n_2", 1e-13, ...
    "f", 3e-1, ...
    "w_f", 4.75e-6, ...
    "L", 1e3, ...
    "N_screens", 50, ...
    "N_subharm", 5, ...
    "has_noise", true, ...
    "eta", 8e-1, ...
    "T", 300, ...
    "R", 100e6, ...
    "delta_f", 10e3, ...
    "N_x", 1024, ...
    "N_y", 1024, ...
    "L_x", 8e0, ...
    "L_y", 8e0, ...
    "sigma", 5e-6, ...
    "gamma", 1e-5, ...
    "N_iter", 100 ...
);

gif_params = Parameters_Gif( ...
    "delay", 0.1, ...
    "name", sprintf( ...
        'spgd_animation_%.3e_%.3e_%.3e_%.3e_%.3e.gif', ...
        all_params.turbulence_params.C_n_2, ...
        all_params.turbulence_params.L_0, ...
        all_params.turbulence_params.l_0, ...
        all_params.path_params.N_screens, ...
        all_params.path_params.N_subharm ...
    ) ...
);

all_meshs = Mesh_All(all_params);

[E_in, F_mode] = original_fields( ...
    all_params, ...
    all_meshs ...
);

E_out = propogate( ...
    E_in, ...
    all_meshs.wave_number_coords, ...
    all_meshs.wave_inv_metric_coords, ...
    all_params.wave_params, ...
    all_params.turbulence_params, ...
    all_params.path_params ...
);

spgd_result = SPGD_algorithm( ...
    E_out, ...
    F_mode, ...
    all_meshs.wave_metric_coords, ...
    all_meshs.lens_metric_coords, ...
    all_params.hyper_params, ...
    all_params.wave_params, ...
    all_params.lens_params, ...
    all_params.noise_params ...
);

fig = figure();
fig.Visible = 'off';
fig.ThemeMode = 'manual';
fig.Theme = 'light';
fig.Color = [1 1 1];
fig.Position = groot().ScreenSize;

I_axes = subplot(1,2,1);
J_axes = subplot(1,2,2);

[I_img, I_mu, I_mc, J_mi] = make_plots( ...
    all_params, ...
    all_meshs, ...
    spgd_result, ...
    I_axes, ...
    J_axes ...
);

make_gif( ...
    hyper_params, ...
    gif_params, ...
    spgd_result, ...
    I_img, ...
    I_mu, ...
    I_mc, ...
    J_mi, ...
    I_axes ...
)

close(fig);