function make_interaction( ...
    all_params, ...
    result, ...
    I_img, ...
    I_mu, ...
    I_mc, ...
    J_mi, ...
    I_axes, ...
    sld ...
)
    sld.Limits = [0, all_params.hyper_params.N_iter];
    sld.Value = 1;
    sld.MajorTicks = 0:all_params.hyper_params.N_iter/10:all_params.hyper_params.N_iter;
    sld.MinorTicks = all_params.hyper_params.N_iter/20:all_params.hyper_params.N_iter/10:all_params.hyper_params.N_iter;
    
    sld.ValueChangingFcn = @(src, evt) update_plots( ...
        src, round(evt.Value), result, I_img, I_mu, I_axes, I_mc, J_mi, all_params.hyper_params.N_iter ...
    );
    
    function update_plots( ...
        src, indx, result, I_img, I_mu, I_axes, I_mc, J_mi, n_iter ...
    )
        if indx < 1, indx = 1; elseif indx > n_iter, indx = n_iter; end
        
        src.Value = indx;
        
        I_img.CData = result.I_hist{indx};
        I_axes.Title.String = sprintf('Интенсивность (итерация %d)', indx);
        
        I_mu.XData = result.u_hist(indx,1);
        I_mu.YData = result.u_hist(indx,2);
        
        I_mc.XData = result.I_cent_hist(indx,1);
        I_mc.YData = result.I_cent_hist(indx,2);
        
        J_mi.XData = indx;
        J_mi.YData = result.J_hist(indx);
    
        drawnow limitrate;
    end
end