function make_gif( ...
    hyper_params, ...
    gif_params, ...
    result, ...
    I_img, ...
    I_mu, ...
    I_mc, ...
    J_mi, ...
    I_axes ...
)
    for iter = 1:1:hyper_params.N_iter
        I_img.CData = result.I_hist{iter};
    
        I_axes.Title.String = sprintf( ...
            'Интенсивность (итерация %d, CE = %.3e)', ...
            iter, result.J_hist(iter) ...
        );
        
        I_mu.XData = result.u_hist(iter,1);
        I_mu.YData = result.u_hist(iter,2);
        
        I_mc.XData = result.I_cent_hist(iter,1);
        I_mc.YData = result.I_cent_hist(iter,2);
        
        J_mi.XData = iter;
        J_mi.YData = result.J_hist(iter);
        
        drawnow;
        
        [A, map] = rgb2ind(frame2im(getframe(fig)), 256);
        
        if iter == 1
            imwrite( ...
                A, map, gif_params.name, 'gif', ...
                'LoopCount', Inf, ...
                'DelayTime', gif_params.delay ...
            );
        else
            imwrite( ...
                A, map, gif_params.name, 'gif', ...
                'WriteMode', 'append', ...
                'DelayTime', gif_params.delay ...
            );
        end
    end
end