function [E_in, F_mode] = original_fields( ...
    all_params, ...
    all_meshs ...
)
    F_mode = gauss2( ...
        all_meshs.lens_metric_coords.X, ...
        all_meshs.lens_metric_coords.Y, ...
        all_params.lens_params.w_f ...
    );
    
    E_in = gauss2( ...
        all_meshs.wave_metric_coords.X, ...
        all_meshs.wave_metric_coords.Y, ...
        all_params.wave_params.w_0 ...
    );
end